### ISSUE TITLE
npm should be run outside of the node repl, in your normal shell.

### ISSUE THREAD

**Issue by Lysander405** [dimotsai/agar-mini-map#44]
when I press cd agar-mini-map-v0.46-win-x64 it says:
 at Object.exports.createScript (vm.js:24:10)
 at REPLServer.defaultEval (repl.js:137:25)
 at bound (domain.js:250:14)
 at REPLServer.runBound [as eval] (domain.js:263:12)
 at REPLServer.<anonymous> (repl.js:392:12)
 at emitOne (events.js:82:20)
 at REPLServer.emit (events.js:169:7)
 at REPLServer.Interface._onLine (readline.js:210:10)
 at REPLServer.Interface._line (readline.js:546:8)
 at REPLServer.Interface._ttyWrite (readline.js:823:1
then when I press npm run or npm build it says:
 > npm run start
npm run start
npm should be run outside of the node repl, in your normal shell.
(Press Control-D to exit.)
>
Please help me...

**Comment by dimotsai** [comment]
Please run your those npm commands under `Windows Command Prompt`

**Comment by dinhtona** [comment]
Tks dimotsai, is work !
